    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatContent: { flex: 1, marginLeft: scale(10) },
  chatTitle: { fontSize: moderateScale(11), fontWeight: '700', color: '#222' },
  chatSubtitle: { fontWeight: '400', color: '#555', fontSize: moderateScale(11) },
  chatBtn: {
    width: scale(38),
    height: scale(38),
    borderRadius: scale(19),
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Footer
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: wp(4),
    paddingTop: hp(1.5),
    paddingBottom: hp(3),
    gap: verticalScale(10),
  },
  downloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E3A8A',
    borderRadius: scale(10),
    paddingVertical: verticalScale(14),
    gap: 8,
  },
  downloadText: { color: '#fff', fontSize: moderateScale(15), fontWeight: '600' },
  doneBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: scale(10),
    paddingVertical: verticalScale(14),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  doneText: { color: '#222', fontSize: moderateScale(15), fontWeight: '500' },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(8),
  },
  modalCard: {
    backgroundColor: '#fff',
    borderRadius: scale(20),
    padding: scale(24),
    alignItems: 'center',
    width: '100%',
  },
  modalIcon: {
    width: scale(64),
    height: scale(64),
    borderRadius: scale(32),
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(16),
  },
  modalTitle: { fontSize: moderateScale(18), fontWeight: '700', color: '#222', marginBottom: 8 },
  modalMessage: { fontSize: moderateScale(13), color: '#666', textAlign: 'center', marginBottom: verticalScale(20) },
  modalBtn: {
    width: '100%',
    backgroundColor: '#F3F4F6',
    paddingVertical: verticalScale(12),
    borderRadius: scale(10),
    alignItems: 'center',
  },
  modalBtnText: { color: '#333', fontSize: moderateScale(14), fontWeight: '600' },
});


